name: Build

on:
  push:
    branches:
      - actions
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 11

   