name: Build

on:
  push:
    branches:
      - actions
  pull_request:

jobs:
 
  Test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Check Java version
      run: java --version

   