name: Build

on:
  push:
    branches:
      - actions
  pull_request:

jobs:
 
  Build:

    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_artifactory_token: '${{secrets.ARTIFACTORY_TOKEN}}'    
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./gradlew build
   